main: main.cpp manager.h manager.cpp gamestate.h gamestate.cpp utilities.cpp utilities.h
	g++ -g -o main main.cpp manager.cpp manager.h gamestate.cpp gamestate.h utilities.cpp utilities.h

clean:
	rm -rf main
