main: main.cpp manager.h manager.cpp gamestate.h gamestate.cpp utilities.cpp utilities.h moves.cpp moves.h boardutils.h game.cpp game.h evaluate.cpp evaluate.h search.cpp search.h
	g++ -g -o main main.cpp manager.cpp manager.h gamestate.h utilities.cpp utilities.h moves.cpp moves.h boardutils.h game.cpp game.h evaluate.cpp evaluate.h search.cpp search.h

clean:
	rm -rf main
